apiVersion: v1
kind: Template
metadata:
  name: "apicast-basicauth-policy"
message: "APIcast BasicAuth Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-basicauth-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'apicast-policy:latest'
    source:
      git:
        uri: https://github.com/samugi/apicast-example-policy.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: ${INPUT_NAMESPACE}
          name: '${INPUT_IMAGE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom-policies
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        namespace: ${OUTPUT_NAMESPACE}
        name: '${OUTPUT_IMAGE}'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        -  bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            namespace: ${OUTPUT_NAMESPACE}
            name: 'apicast-policy:latest'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/basicauth
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/example/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src
        USER root

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          namespace: ${INPUT_NAMESPACE}
          name: '${INPUT_IMAGE}'
      type: Docker
    triggers:
      - type: ConfigChange

parameters:
- name: INPUT_NAMESPACE
  required: true
  description: Input Namespace (OpenShift Project name) from which the base image is loaded
- name: OUTPUT_NAMESPACE
  required: true
  description: Output Namespace (OpenShift Project name)
- name: INPUT_IMAGE
  required: true
  description: Input image name
- name: OUTPUT_IMAGE
  required: true
  description: Output image name